### PR TITLE
Fix error that cause 0 timestamp and "市" in city field

### PR DESCRIPTION
**Pull request by Vopaaz**

### CODE REVIEW

**Comment by Vopaaz** [comment]
确实是我的锅！！【x

**Comment by zhaofeng-shu33** [comment]
Can you explain how to run the data migration python code in the README documentation?
I am new to this project and a little bit confused.

**Comment by Vopaaz** [comment]
> Can you explain how to run the data migration python code in the README documentation?
> I am new to this project and a little bit confused.

Added in the latest commit.

**Comment by zhaofeng-shu33** [comment]
I wonder what is the purpose of using Python to put data into the database? We can execute [sql data files](https://github.com/Glacier-Ice/data-sci-api/tree/master/db/data) to do this.

**Comment by Vopaaz** [comment]
> I wonder what is the purpose of using Python to put data into the database? We can execute [sql data files](https://github.com/Glacier-Ice/data-sci-api/tree/master/db/data) to do this.

Because the data is dynamically updated. We pull data from Baidu's API each day, reshape into the desired format and store it into the DB.

**Comment by zhaofeng-shu33** [comment]
```
[feng@bcm point-to-point-migration]$ python integration.py 
Traceback (most recent call last):
  File "integration.py", line 101, in <module>
    res = get_p2p_overall_dataframe()
  File "integration.py", line 55, in get_p2p_overall_dataframe
    history_curve = load_history(date, row.adcode)
  File "integration.py", line 26, in load_history
    update_history_if_outdated("in", city_id)
  File "integration.py", line 18, in update_history_if_outdated
    with open(path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './temp/move_in_history_110000.txt'
```
The first time I run the migration code. Please help.

**Comment by Vopaaz** [comment]
Would you please try the latest version? @zhaofeng-shu33

**Comment by Vopaaz** [comment]
By the way if you want to run the code for test purpose, please comment those lines that actually dump data into the DB.

**Comment by zhaofeng-shu33** [comment]
> Would you please try the latest version? @zhaofeng-shu33

I will try again.

**Comment by zhaofeng-shu33** [comment]
So why sleep every 1 second ? https://github.com/Glacier-Ice/data-sci-api/blob/fix-index-data/src-etl/point-to-point-migration/crawl.py#L22

**Comment by zhaofeng-shu33** [comment]
After I comment the sleep code, I get a lot of txt files after running `python integration.py`. So how can I put those txt data into database?

**Comment by Vopaaz** [comment]
> So why sleep every 1 second ? https://github.com/Glacier-Ice/data-sci-api/blob/fix-index-data/src-etl/point-to-point-migration/crawl.py#L22

If you request the API too frequently you will be blocked.

**Comment by Vopaaz** [comment]
> After I comment the sleep code, I get a lot of txt files after running `python integration.py`. So how can I put those txt data into database?

https://github.com/Glacier-Ice/data-sci-api/blob/fix-index-data/src-etl/point-to-point-migration/main.py does this.

**Comment by zhaofeng-shu33** [comment]
For `main.py` I found you load the database config file from environment variable. But why you use `json.loads`? It is actually loading from string.

**Comment by Vopaaz** [comment]
> For `main.py` I found you load the database config file from environment variable. But why you use `json.loads`? It is actually loading from string.

In the production environment, the config is indeed stored directly in the environment variable, instead of a path.

**Comment by zhaofeng-shu33** [comment]
> > For `main.py` I found you load the database config file from environment variable. But why you use `json.loads`? It is actually loading from string.
> 
> In the production environment, the config is indeed stored directly in the environment variable, instead of a path.

So I have to save the json string in this environment variable instead of a json file path?

**Comment by Vopaaz** [comment]
> > > For `main.py` I found you load the database config file from environment variable. But why you use `json.loads`? It is actually loading from string.
> > 
> > 
> > In the production environment, the config is indeed stored directly in the environment variable, instead of a path.
> 
> So I have to save the json string in this environment variable instead of a json file path?

That's your choice. Personally I have a local branch using `json.load` and set the `CONFIG_PATH` as the config file path. After development, I cherry-pick all necessary commits to the remote-tracking branch and push.

**Comment by zhaofeng-shu33** [comment]
That's cool

**Comment by zhaofeng-shu33** [comment]
I find the script in `main.py` creates two tables "migration_index" and "p2p_migration". What's the purpose of these two tables? Are they used in the API server?

**Comment by Stockard** [comment]
Hi Zhao Feng. very good question. apparently we need a guideline to introduce the tables.
p2p_migration is for migration index from city to city, which starts from late February 2020.
while migration_index stores outflow and inflow index from one city, and could dates back to 2019.

**Comment by zhaofeng-shu33** [comment]
I have added some documentation.

**Pull request merged**
